server:
  port: 8081
spring:
  application:
    name: Midnight-Delights
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.143.214.16:3306/midnight_delights?useSSL=false&serverTimezone=UTC
    username: root
    password: cdp1161707735
  redis:
    host: 43.143.214.16
    port: 6379
    password: adminRedisWeb
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
mybatis-plus:
  type-aliases-package: com.bjut.entity
logging:
  level:
    com.bjut: debug
  pattern:
    dateformat: mm:ss.SSS